# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf3faad5b85c9e8a886d763c0b8c6260458eebab70cdc99abf631fde52df7b765afb071aa0c19ce7c140e64847c1aceeb0ad8158758912bd27b604cee81f15c7

test:
  secret_key_base: 4ef2562415ba5ac17bde2319997a5d50fed397a7b200d573cbb5366903b7b81c79463349890ef7d11cef83ddb6762a3fc9c30e9fd07242c5f5d603dc6b00d32a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
